name: Build Common Component

permissions:
  actions: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      component_name:
        type: string
        required: true
        default: zsy
      octet:
        type: string
        required: true
        default: patch

env:
  GPR_USERNAME: ${{github.repository_owner}}
  GPR_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-common-component:
    runs-on: codebuild-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: bump.sh
        run: |
          pwd
          chmod +x .github/scripts/bump.sh
          .github/scripts/bump.sh ${{github.event.inputs.component_name}} ${{github.event.inputs.octet}} develop
