name: CI api component scheduled

on:
  workflow_dispatch:

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      commit_count: ${{ steps.get_commit_count.outputs.commit_count }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Get commits in the last day
        id: get_commit_count
        run: |
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          past_time=$(date -u -d "$current_time - 1 day" +"%Y-%m-%dT%H:%M:%SZ")
          commits=$(git log --since="$past_time" --until="$current_time")
          echo "$commits" > commits.txt
          commit_count=$(echo "$commits" | grep -c '^commit')
          echo "commit_count=$commit_count" >> $GITHUB_ENV
        env:
          GITHUB_ENV: ${{ github.env }}

  build:
    runs-on: ubuntu-latest
    needs: check_commit
    if: needs.check_commit.outputs.commit_count > 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "21"
          server-id: gradle
          settings-path: ${{ github.workspace }}
          cacerts: false
      #PJ内ではここでcatoの証明書をkeytoolコマンドでインポートしています
      
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.5-bin.zip
          unzip -d /opt/gradle gradle-8.5-bin.zip
          echo "PATH=$PATH:/opt/gradle/gradle-8.5/bin" >> $GITHUB_ENV
      
      - name: Build and Publish Jar (zsy)
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: zsy
        run: |
          gradle ysyJar -Pjarversion=${{ env.NEW_VERSION }}
          gradle publish

      - name: Build and Publish Jar (ysy)
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ysy
        run: |
          gradle ysyJar -PJarversion=${{ env.NEW_VERSION }}
          gradle publish