name: Build Common Component

permissions:
  actions: write

on:
  workflow_dispatch:

env:
  GPR_USERNAME: ${{github.repositry_owner}}
  GPR_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build-common-component:
    runs-on: codebuild-actions-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: bump.sh
        run: |
          pwd
          chmod +x .github/scripts/bump.sh
          .github/scripts/bump.sh zsy patch
