name: Dependency Submission

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositry
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "21"
          server-id: gradle
          settings-path: ${{ github.workspace }}
          cacerts: false
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
