name: Comment on PR

on:
  pull_request:
    types: [opened]
    branches:
      - develop

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Add Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: 'リリースを行う部品、イメージを指定してください。'
            })